[package]
name = "twitch_chatbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.20.0"
url = "2.4.0"
regex = "1.9.1"